package enums

const (
	CACHE_LOGIN_ERROR    = "CACHE_LOGIN_ERROR"     //登录密码错误
	CACHE_NOTICE_PRE     = "CACHE_NOTICE_PRE"      //通知前缀
	CACHE_CCVISITBAN_PRE = "CACHE_CCVISITBAN_PRE_" //CC封禁前缀
	CACHE_TOKEN          = "CACHE_TOKEN"           //鉴权信息
	CACHE_DNS_BOT_IP     = "CACHE_DNS_BOT_IP"      //IP反向域名解析
	CACHE_DNS_NORMAL_IP  = "CACHE_DNS_NORMAL_IP"   //正常IP
	CACHE_CAPTCHA_TRY    = "CACHE_CAPTCHA_TRY"     //验证码临时
	CACHE_CAPTCHA_PASS   = "CACHE_CAPTCHA_PASS"    //通过验证的码
	CACHE_ANNOUNCEMENT   = "CACHE_ANNOUNCEMENT"    //公告数据
	CACHE_WEBFILE        = "CACHE_WEBFILE"
)
