// Code generated by protoc-gen-go-grpc. (手写版本)

package proto

import (
	"context"
	"encoding/json"

	plugininterface "SamWaf/plugin/interface"

	"google.golang.org/grpc"
)

// IPFilterPluginServer gRPC 服务端接口
type IPFilterPluginServer interface {
	Name(context.Context, *Empty) (*PluginInfo, error)
	Init(context.Context, *InitRequest) (*InitResponse, error)
	Filter(context.Context, *IPFilterRequest) (*IPFilterResponse, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	HealthCheck(context.Context, *Empty) (*Empty, error)
}

// IPFilterPluginClient gRPC 客户端接口
type IPFilterPluginClient interface {
	Name(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error)
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	Filter(ctx context.Context, in *IPFilterRequest, opts ...grpc.CallOption) (*IPFilterResponse, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

// IPFilterRequest protobuf 消息
type IPFilterRequest struct {
	Ip          string            `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	RequestPath string            `protobuf:"bytes,2,opt,name=request_path,json=requestPath,proto3" json:"request_path,omitempty"`
	UserAgent   string            `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Extra       map[string]string `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *IPFilterRequest) Reset()         {}
func (x *IPFilterRequest) String() string { return "IPFilterRequest" }
func (x *IPFilterRequest) ProtoMessage()  {}

// IPFilterResponse protobuf 消息
type IPFilterResponse struct {
	Allowed   bool   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason    string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	RiskLevel int32  `protobuf:"varint,3,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
}

func (x *IPFilterResponse) Reset()         {}
func (x *IPFilterResponse) String() string { return "IPFilterResponse" }
func (x *IPFilterResponse) ProtoMessage()  {}

// PluginInfo protobuf 消息
type PluginInfo struct {
	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Type    string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *PluginInfo) Reset()         {}
func (x *PluginInfo) String() string { return "PluginInfo" }
func (x *PluginInfo) ProtoMessage()  {}

// InitRequest protobuf 消息
type InitRequest struct {
	ConfigJson string `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
}

func (x *InitRequest) Reset()         {}
func (x *InitRequest) String() string { return "InitRequest" }
func (x *InitRequest) ProtoMessage()  {}

// InitResponse protobuf 消息
type InitResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *InitResponse) Reset()         {}
func (x *InitResponse) String() string { return "InitResponse" }
func (x *InitResponse) ProtoMessage()  {}

// Empty protobuf 消息
type Empty struct{}

func (x *Empty) Reset()         {}
func (x *Empty) String() string { return "Empty" }
func (x *Empty) ProtoMessage()  {}

// GRPCServer 插件端的 gRPC 服务器适配器
type GRPCServer struct {
	Impl plugininterface.IPFilterPlugin
}

func (m *GRPCServer) Name(ctx context.Context, req *Empty) (*PluginInfo, error) {
	return &PluginInfo{
		Name:    m.Impl.Name(),
		Version: m.Impl.Version(),
		Type:    m.Impl.Type(),
	}, nil
}

func (m *GRPCServer) Init(ctx context.Context, req *InitRequest) (*InitResponse, error) {
	var config map[string]interface{}
	if err := json.Unmarshal([]byte(req.ConfigJson), &config); err != nil {
		return &InitResponse{Success: false, Error: err.Error()}, nil
	}

	if err := m.Impl.Init(config); err != nil {
		return &InitResponse{Success: false, Error: err.Error()}, nil
	}

	return &InitResponse{Success: true}, nil
}

func (m *GRPCServer) Filter(ctx context.Context, req *IPFilterRequest) (*IPFilterResponse, error) {
	// 转换请求
	pluginReq := &plugininterface.IPFilterRequest{
		IP:          req.Ip,
		RequestPath: req.RequestPath,
		UserAgent:   req.UserAgent,
		Extra:       make(map[string]interface{}),
	}
	for k, v := range req.Extra {
		pluginReq.Extra[k] = v
	}

	// 调用插件
	resp, err := m.Impl.Filter(ctx, pluginReq)
	if err != nil {
		return nil, err
	}

	// 转换响应
	return &IPFilterResponse{
		Allowed:   resp.Allowed,
		Reason:    resp.Reason,
		RiskLevel: int32(resp.RiskLevel),
	}, nil
}

func (m *GRPCServer) Shutdown(ctx context.Context, req *Empty) (*Empty, error) {
	return &Empty{}, m.Impl.Shutdown()
}

func (m *GRPCServer) HealthCheck(ctx context.Context, req *Empty) (*Empty, error) {
	return &Empty{}, m.Impl.HealthCheck(ctx)
}

// GRPCClient 主程序端的 gRPC 客户端适配器
type GRPCClient struct {
	client IPFilterPluginClient
}

// NewGRPCClient 创建 GRPCClient 实例
func NewGRPCClient(client IPFilterPluginClient) *GRPCClient {
	return &GRPCClient{client: client}
}

func (m *GRPCClient) Name() string {
	resp, err := m.client.Name(context.Background(), &Empty{})
	if err != nil {
		return ""
	}
	return resp.Name
}

func (m *GRPCClient) Version() string {
	resp, err := m.client.Name(context.Background(), &Empty{})
	if err != nil {
		return ""
	}
	return resp.Version
}

func (m *GRPCClient) Type() string {
	resp, err := m.client.Name(context.Background(), &Empty{})
	if err != nil {
		return ""
	}
	return resp.Type
}

func (m *GRPCClient) Init(config map[string]interface{}) error {
	configJSON, err := json.Marshal(config)
	if err != nil {
		return err
	}

	resp, err := m.client.Init(context.Background(), &InitRequest{
		ConfigJson: string(configJSON),
	})
	if err != nil {
		return err
	}

	if !resp.Success {
		return json.Unmarshal([]byte(resp.Error), &err)
	}

	return nil
}

func (m *GRPCClient) Filter(ctx context.Context, req *plugininterface.IPFilterRequest) (*plugininterface.IPFilterResponse, error) {
	// 转换请求
	grpcReq := &IPFilterRequest{
		Ip:          req.IP,
		RequestPath: req.RequestPath,
		UserAgent:   req.UserAgent,
		Extra:       make(map[string]string),
	}
	for k, v := range req.Extra {
		if str, ok := v.(string); ok {
			grpcReq.Extra[k] = str
		}
	}

	// 调用 gRPC
	resp, err := m.client.Filter(ctx, grpcReq)
	if err != nil {
		return nil, err
	}

	// 转换响应
	return &plugininterface.IPFilterResponse{
		Allowed:   resp.Allowed,
		Reason:    resp.Reason,
		RiskLevel: int(resp.RiskLevel),
	}, nil
}

func (m *GRPCClient) Shutdown() error {
	_, err := m.client.Shutdown(context.Background(), &Empty{})
	return err
}

func (m *GRPCClient) HealthCheck(ctx context.Context) error {
	_, err := m.client.HealthCheck(ctx, &Empty{})
	return err
}

// 服务注册和客户端创建函数

// RegisterIPFilterPluginServer 注册服务
func RegisterIPFilterPluginServer(s *grpc.Server, srv IPFilterPluginServer) {
	desc := &grpc.ServiceDesc{
		ServiceName: "proto.IPFilterPlugin",
		HandlerType: (*IPFilterPluginServer)(nil),
		Methods: []grpc.MethodDesc{
			{
				MethodName: "Name",
				Handler:    _IPFilterPlugin_Name_Handler,
			},
			{
				MethodName: "Init",
				Handler:    _IPFilterPlugin_Init_Handler,
			},
			{
				MethodName: "Filter",
				Handler:    _IPFilterPlugin_Filter_Handler,
			},
			{
				MethodName: "Shutdown",
				Handler:    _IPFilterPlugin_Shutdown_Handler,
			},
			{
				MethodName: "HealthCheck",
				Handler:    _IPFilterPlugin_HealthCheck_Handler,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "ip_filter.proto",
	}
	s.RegisterService(desc, srv)
}

func _IPFilterPlugin_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPFilterPluginServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IPFilterPlugin/Name",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPFilterPluginServer).Name(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPFilterPlugin_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPFilterPluginServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IPFilterPlugin/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPFilterPluginServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPFilterPlugin_Filter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPFilterPluginServer).Filter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IPFilterPlugin/Filter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPFilterPluginServer).Filter(ctx, req.(*IPFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPFilterPlugin_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPFilterPluginServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IPFilterPlugin/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPFilterPluginServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPFilterPlugin_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPFilterPluginServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IPFilterPlugin/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPFilterPluginServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ipFilterPluginClient 是客户端实现
type ipFilterPluginClient struct {
	cc grpc.ClientConnInterface
}

// NewIPFilterPluginClient 创建客户端
func NewIPFilterPluginClient(cc grpc.ClientConnInterface) IPFilterPluginClient {
	return &ipFilterPluginClient{cc}
}

func (c *ipFilterPluginClient) Name(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, "/proto.IPFilterPlugin/Name", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipFilterPluginClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, "/proto.IPFilterPlugin/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipFilterPluginClient) Filter(ctx context.Context, in *IPFilterRequest, opts ...grpc.CallOption) (*IPFilterResponse, error) {
	out := new(IPFilterResponse)
	err := c.cc.Invoke(ctx, "/proto.IPFilterPlugin/Filter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipFilterPluginClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.IPFilterPlugin/Shutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipFilterPluginClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.IPFilterPlugin/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
